export const SET_USER_DATA = '[USER] SET DATA';
export const REMOVE_USER_DATA = '[USER] REMOVE DATA';
export const USER_LOGGED_OUT = '[USER] LOGGED OUT';

export default {USER_LOGGED_OUT, REMOVE_USER_DATA, SET_USER_DATA}
